provider "nirmata" {
  // Set NIRMATA_TOKEN with your API Key
  // You can also set NIRMATA_URL with the Nirmata URL address
}
resource "nirmata_gke_clusterType" "cluster-type-gke" {
  // Note that you may want to create your cluster type in the UI instead of creating them in terraform.
  name       = "gke-cluster-type"
  version  = "" //The version of Kubernetes that should be used for this cluster.
  credentials = "" //cloud credentials that hosts this cluster
  region= "" //The  region into which the cluster should be deployed
  machinetype = ""
  disksize = 10
}

resource "nirmata_ProviderManaged_cluster" "cluster-1" {
  name       = "tf-gke-cluster"
  // The type_selector may be an existing cluster type instead of the above autogenerated.
  type_selector  =  nirmata_gke_clusterType.name
  node_count = 1
}

